### PUT to store something in the cache
PUT http://127.0.0.1:8080/cache/myKey/This%20is%20a%20string
###

### GET request to retrieve the data
GET http://127.0.0.1:8080/cache/myKey
###

### create 1000 stock symbols in topic stockvalues (has to be created before)
POST http://127.0.0.1:8080/kafka/sendStockSymbols/stockvalues/1000
###

### receive stock symbols within 4000 msec from topic stockvalues
GET http://127.0.0.1:8080/kafka/receiveStockSymbols/stockvalues/4000
###